### ISSUE TITLE
My Missions - "Status" text not aligned under status column

### ISSUE THREAD

**Issue by RogueEnterprise** [Zorbane/foundrymissions#12]
The status text is not aligned under the status column when viewing My Missions

Steps
1. Be an existing user with at least 1 mission
2. Navigate to http://fmv001.azurewebsites.net/manage and click My Missions

Result: Status is not showing under the "Status" column
Expected: The status and the status column header align
![align](https://cloud.githubusercontent.com/assets/19982318/16351643/ffd1573a-3a1b-11e6-8b9a-9ae17761b90b.PNG)

**Comment by aaronliunumber2** [comment]
It was reading CSS that wasn't intended for that.  Itw asn't supposed to be red either.  Changed the class of the div
