### ISSUE TITLE
Replace minimum level selector with dropdown

### ISSUE THREAD

**Issue by RogueEnterprise** [Zorbane/foundrymissions#18]
Please replace the minimum level selector with a new dropdown menu in the following locations:
- Mission submission/edit
- Advanced Search

The selections should be:
Any Level
16+
21+
31+
35+
41+
46+
50+
51+
57+

**Comment by aaronliunumber2** [comment]
This is done but Any Level = 1 right now

**Comment by aaronliunumber2** [comment]
This is done, but not deployed (that will be later today)
