### ISSUE TITLE
Advanced search does not return results that fit all criteria

### ISSUE THREAD

**Issue by RogueEnterprise** [Zorbane/foundrymissions#19]
Advanced search appears to be returning results that match any of the criteria in search, but not all.

Steps to reproduce:
1. Go to the advanced search page
2. Search for two tags: example "Custom Aliens" and "Cardassians"

Result: Missions are returned that have either of those two tags
Expected: Missions are returned that contain both of those tags

**Comment by aaronliunumber2** [comment]
Fixed, it was only searching for any match, now it must match all
