### ISSUE TITLE
Sign off on each page for SBUGC soft launch

### ISSUE THREAD

**Issue by aaronliunumber2** [Zorbane/foundrymissions#20]
Homepage
Mission Details
Submit Mission
Edit Mission
(Simple) Search Results
Advanced Search
Advanced Search Results
Login
Control Panel - My Account
Control Panel - My Missions
Control Panel - Mission Approval
Control Panel  - Author List
Contact Us

**Comment by RogueEnterprise** [comment]
Not signed off:
None

Signed off:
Homepage (logo update later)
Login
Submission
Edit Mission
Control Panel - My Account
Control Panel - My Missions
Control Panel - Mission Approval
Control Panel - Author List
Contact Us
Mission Details
Simple search results/Advanced search results

**Comment by RogueEnterprise** [comment]
All pages are now signed off.
