### ISSUE TITLE
Clicking author names on main page results in error

### ISSUE THREAD

**Issue by RogueEnterprise** [Zorbane/foundrymissions#4]
Clicking author names on the main page results in an error.

Steps to reproduce:
1. Go to the main page (currently http://fmv001.azurewebsites.net/)
2. Select the author name in any of the listings

Result: Error page starting with "Server Error in '/' Application."
Expected: Search results listing all missions by that author (probably via advanced search)

**Comment by aaronliunumber2** [comment]
For now it will just shunt off to search?q=authorname

when advanced search is implemented it will shunt it there

**Comment by RogueEnterprise** [comment]
Advanced search is implemented, this is ready to be fixed.

**Comment by aaronliunumber2** [comment]
Ok this is not as easy as I thought...will discuss with you on discord.

**Comment by RogueEnterprise** [comment]
Right now I think it's OK that it goes to simple search. I think that this is closable pending revamp to advanced search.
