### ISSUE TITLE
Write short description for websites that want to link to us

### ISSUE THREAD

**Issue by aaronliunumber2** [Zorbane/foundrymissions#47]
Right now its for lootcritter but other sites may want this too

ie https://lootcritter.com/resources/

**Comment by RogueEnterprise** [comment]
Copy draft:

FoundryMissions.com provides a place outside the game where Star Trek Online Foundry authors can list their missions with images, additional tags and other details that make them more searchable compared to the in-game interface. Players of Foundry missions can use detailed search criteria to find missions that suit their particular taste.
