### ISSUE TITLE
Add videos to missions

### ISSUE THREAD

**Issue by aaronliunumber2** [Zorbane/foundrymissions#56]

**Comment by RogueEnterprise** [comment]
So this made it to production, but the lack of play arrows makes them seem like a screenshot. Any solution?

**Comment by aaronliunumber2** [comment]
I can probably put a play button overlay on it

**Comment by RogueEnterprise** [comment]
Confirmed overlay fix! Last issue is that play button must be clicked twice to get the video to play, some kind of popup issue. Can that be addressed?

**Comment by aaronliunumber2** [comment]
Unknown.  I'm currently using blueimp gallery.  Will need to see if i can configure it

**Comment by aaronliunumber2** [comment]
maybe this?  i will try tomorrow

https://wordpress.org/support/topic/autoplay-for-video/?replies=5

**Comment by RogueEnterprise** [comment]
Poking this one!

**Comment by aaronliunumber2** [comment]
Fixed the double click to play thing
