### ISSUE TITLE
Mission detail display issues in smaller viewpoints

### ISSUE THREAD

**Issue by RogueEnterprise** [Zorbane/foundrymissions#6]
When viewing the mission detail page, there are many components that do not look correct when viewing the page from any viewpoint except the maximum size.

Use the following example: http://fmv001.azurewebsites.net/missions/purity-i-of-denial

Issue 1: When viewing in the second-to-largest viewpoint, mission tags overlaps with media.
Issue 2: When viewing in the third-to-largest viewpoint, the mission name is above the header and unreadable, and the media extends out too far and overlaps tags.
Issue 3: When viewing in the fourth-to-largest viewpoint (and smaller), multiple elements overlap

See screenshots for each issue
![3](https://cloud.githubusercontent.com/assets/19982318/16135311/94957fcc-33d7-11e6-8bc1-783f2482b93f.PNG)
![2](https://cloud.githubusercontent.com/assets/19982318/16135312/94962fbc-33d7-11e6-8b93-0462b81e3ac5.PNG)
![1](https://cloud.githubusercontent.com/assets/19982318/16135313/949922b2-33d7-11e6-8acc-7e84fa32c25a.PNG)

**Comment by aaronliunumber2** [comment]
Fixed both the header AND the image list
