### ISSUE TITLE
Error with sending email via smtp

### ISSUE THREAD

**Issue by aaronliunumber2** [Zorbane/foundrymissions#63]
![image](https://user-images.githubusercontent.com/8999201/55377708-0c1f8f80-54cb-11e9-9c7e-50df96d7051f.png)

**Comment by Zorbane** [comment]
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
--

**Comment by aaronliunumber2** [comment]
Unable to read data from the transport connection: net_io_connectionclosed.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.IO.IOException: Unable to read data from the transport connection: net_io_connectionclosed.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 


[IOException: Unable to read data from the transport connection: net_io_connectionclosed.]
   System.Net.Mail.SmtpReplyReaderFactory.ProcessRead(Byte[] buffer, Int32 offset, Int32 read, Boolean readLine) +712
   System.Net.Mail.SmtpReplyReaderFactory.ReadLines(SmtpReplyReader caller, Boolean oneLine) +305
   System.Net.Mail.SmtpReplyReaderFactory.ReadLine(SmtpReplyReader caller) +23
   System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint) +752
   System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint) +279
   System.Net.Mail.SmtpClient.GetConnection() +54
   System.Net.Mail.SmtpClient.Send(MailMessage message) +1841

[SmtpException: Failure sending mail.]
   System.Net.Mail.SmtpClient.Send(MailMessage message) +2777
   FoundryMissionsCom.Helpers.EmailHelper.SendEmail(List`1 recipients, String subject, String body) +395
   FoundryMissionsCom.Controllers.<Register>d__15.MoveNext() +1126
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13891908
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult) +93
   System.Web.Mvc.Async.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult) +22
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +69
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +72
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +386
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +69
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +38
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +186
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +59
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +65
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +53
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +38
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +44
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +65
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +38
   System.Web.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar) +178

**Comment by aaronliunumber2** [comment]
Dear Aaron Liu,

Hello,
Thank you for contacting Seekdotnet Technical Support.
Please look into our picture that we've attached on this ticket.
From our iis web server in smtp email menu, it showing an error in line 40 in your web.config file related to your script enableSsl="false" .
For now we have removed this script enableSsl="false" and the error is not showing anymore in our IIS web server.
We have also tried to telnet from your web server to your mail server and the telnet connection result is succesfull which means there is no problem for the mail connection from web server to your mail server.
Perhaps, if you still got these error, please advise us the step to reproduce the error.
Please kindly check it again at your end.

Thank you

Kind Regards
Seekdotnet
Support Team
